project/project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('story.urls'))
]

project/story/urls.py
from django.urls import path
from story import views
app_name="story"
urlpatterns = [
    
    path('',views.story_list,name='story_list'),
    path('story/<slug:category_slug>',views.story_list,name="story_category"),
    path('<int:id>/',views.story_detail,name='story_detail'),

]

project/story/models.py
from django.db import models
from django.urls import reverse
# Create your models here.
class Category(models.Model):
    name=models.CharField(max_length=150,db_index=True,)
    slug=models.SlugField(unique=True)
    class Meta:
        ordering=('-name',)
    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('story:story_category',args=[self.slug,])
class Story(models.Model):
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    title=models.CharField(max_length=150)
    body=models.TextField()
    des=models.TextField()
    publish=models.DateTimeField(auto_now_add=True)
    class Meta:
        ordering=('publish',)
    def __str__(self):
        return self.title
def get_absolute_url(self):
    return reverse('story:story_details',args=[self.id,])

project/story/views.py
from unicodedata import category
from django.shortcuts import render,get_object_or_404
from .models import *
# Create your views here.
def story_list(request,category_slug=None):
    category=None
    categories=Category.objects.all()
    story=Story.objects.all()
    if category_slug:
        category=get_object_or_404(Category,slug=category_slug)
        story=Story.filter(category=category)
    return render(request,'story/story_list.html',{'categories':categories,'story':story,'category':category})
def story_detail(request,id):
    story=get_object_or_404(Story,id=id)
    return render(request,'story/story_detail.html',{'story':story})
    

project/story/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>Shivam Story Book Website</title>
  </head>
  <body>
    <nav class="navbar navbar-light bg-light">
        <span class="navbar-brand mb-0 h1">
            Story Book 
        </span>
    </nav>
     {% block body %} 
        
     {% endblock body %} 
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    -->
  </body>
</html>

project/story/templates/story/story_detail.html
{% extends 'base.html' %} 

{% block title %} 
{{story.title}}
{% endblock %} 

{% block body %} 
<div class="container">
    <h2>{{story.title}}</h2>
    <p class="lead">{{story.body}}</p>
</div>
{% endblock %} 

project/story/templates/story/story_list.html
{% extends 'base.html' %} 

{% block title %}

{% endblock %} 

{% block body %} 
<div class="jumbotron">
    <h3>Categories</h3>
    <ul>
        <li>
            <a href="{% url 'story:story_list' %}">All</a>
        </li>
        <li>
            {% for x in categories %} 
                <li>
                    <a href="{{x.get_absolute_url}}">{{x.name}}</a>
                </li>
            {% endfor %}  
        </li>
    </ul>
</div>
<div>
    <hr>
    <h3>
        {% if category %} 
        {{category.name}}
    {% else %} 
    All-Story 
    {% endif %}
    </h3>
    <hr>
    {% for x in story %}
    <div class="mt-3">
    <a href="{{x.get_absolute_url}}"><h2>{{x.name}}</h2></a>
    <p>{{x.des}}</p>
</div>
    {% endfor %}
</div>
{% endblock %}  

project/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Shivam Story Book Website</title>
</head>
<body>
    
</body>
</html>